import random

accept_languages = [
    'en-US', 'en-GB', 'en-CA', 'en-AU', 'en-NZ', 'en',
    'fr-FR', 'fr-CA', 'fr',
    'es-ES', 'es-MX', 'es',
    'de-DE', 'de',
    'it-IT', 'it',
    'pt-PT', 'pt-BR', 'pt',
    'nl-NL', 'nl',
    'sv-SE', 'sv',
    'no-NO', 'no',
    'da-DK', 'da',
    'fi-FI', 'fi',
    'pl-PL', 'pl',
    'cs-CZ', 'cs',
    'hu-HU', 'hu',
    'ro-RO', 'ro',
    'tr-TR', 'tr',
    'ru-RU', 'ru',
    'ja-JP', 'ja',
    'ko-KR', 'ko',
    'zh-CN', 'zh-TW', 'zh',
    'ar-SA', 'ar',
    'he-IL', 'he',
    'af', 'af-ZA',
    'am', 'am-ET',
    'ar', 'ar-AE', 'ar-BH', 'ar-DZ', 'ar-EG', 'ar-IQ', 'ar-JO', 'ar-KW', 'ar-LB', 'ar-LY', 'ar-MA', 'ar-OM', 'ar-QA', 'ar-SA', 'ar-SD', 'ar-SY', 'ar-TN', 'ar-YE',
    'as', 'as-IN',
    'az', 'az-AZ', 'az-Latn', 'az-Latn-AZ',
    'be', 'be-BY',
    'bg', 'bg-BG',
    'bn', 'bn-BD', 'bn-IN',
    'bs', 'bs-BA',
    'ca', 'ca-ES',
    'cs', 'cs-CZ',
    'cy', 'cy-GB',
    'da', 'da-DK',
    'de', 'de-AT', 'de-CH', 'de-DE', 'de-LI', 'de-LU',
    'el', 'el-GR',
    'en', 'en-AU', 'en-BZ', 'en-CA', 'en-CB', 'en-GB', 'en-IE', 'en-JM', 'en-NZ', 'en-PH', 'en-TT', 'en-US', 'en-ZA', 'en-ZW',
    'eo',
    'es', 'es-AR', 'es-BO', 'es-CL', 'es-CO', 'es-CR', 'es-DO', 'es-EC', 'es-ES', 'es-GT', 'es-HN', 'es-MX', 'es-NI', 'es-PA', 'es-PE', 'es-PR', 'es-PY', 'es-SV', 'es-UY', 'es-VE',
    'et', 'et-EE',
    'eu', 'eu-ES',
    'fa', 'fa-IR',
    'fi', 'fi-FI',
    'fo', 'fo-FO',
    'fr', 'fr-BE', 'fr-CA', 'fr-CH', 'fr-FR', 'fr-LU', 'fr-MC',
    'fy', 'fy-NL',
    'ga', 'ga-IE',
    'gd', 'gd-GB',
    'gl', 'gl-ES',
    'gu', 'gu-IN',
    'he', 'he-IL',
    'hi', 'hi-IN',
    'hr', 'hr-BA', 'hr-HR',
    'hu', 'hu-HU',
    'hy', 'hy-AM',
    'id', 'id-ID',
    'is', 'is-IS',
    'it', 'it-CH', 'it-IT',
    'ja', 'ja-JP',
    'jv', 'jv-ID',
    'ka', 'ka-GE',
    'kk', 'kk-KZ',
    'kn', 'kn-IN',
    'ko', 'ko-KR',
    'ku', 'ku-TR',
    'ky',
]


